### ISSUE TITLE
Decode in RLP package does not work

### ISSUE THREAD

**Issue by petr-hanzl** [Fantom-foundation/Substate#52]
[Decode](https://github.com/Fantom-foundation/Substate/blob/dfad4633950355a1d058658d9b4699fd7d8cb2a9/rlp/rlp.go#L28) inside RLP package does not work. It does not fill the data into the struct.

**Comment by evgensheff** [comment]
@petr-hanzl I added unit tests to check the encoding from the original library and made a couple of edits, now the encoding should not differ at all

#53 and I also made some changes in Decode function and added some unit tests for it as well

Let me know if it works.

**Comment by petr-hanzl** [comment]
Resolved in #53
